// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "App Store and iCloud revenue make the margins look great.",
                            CreatedOn = new DateTime(2025, 1, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            StockId = 1,
                            Title = "Services keep growing"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Waiting for a pullback before adding more.",
                            CreatedOn = new DateTime(2025, 1, 12, 14, 5, 0, 0, DateTimeKind.Unspecified),
                            StockId = 1,
                            Title = "Pricey right now"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Cloud growth plus Copilot upsell looks solid.",
                            CreatedOn = new DateTime(2025, 1, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 2,
                            Title = "Azure is the story"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Data center revenue is carrying everything.",
                            CreatedOn = new DateTime(2025, 1, 18, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            StockId = 3,
                            Title = "AI demand"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Big swings around earnings, size positions carefully.",
                            CreatedOn = new DateTime(2025, 1, 20, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            StockId = 3,
                            Title = "Volatile"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Price cuts are hurting auto gross margin.",
                            CreatedOn = new DateTime(2025, 1, 22, 13, 10, 0, 0, DateTimeKind.Unspecified),
                            StockId = 4,
                            Title = "Margins under pressure"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Two high-margin engines under a retail business.",
                            CreatedOn = new DateTime(2025, 1, 25, 8, 55, 0, 0, DateTimeKind.Unspecified),
                            StockId = 5,
                            Title = "AWS + ads"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Strong capital position and a reliable dividend.",
                            CreatedOn = new DateTime(2025, 1, 28, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            StockId = 6,
                            Title = "Best-run bank"
                        },
                        new
                        {
                            Id = 9,
                            Content = "60+ years of dividend increases, boring in a good way.",
                            CreatedOn = new DateTime(2025, 2, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 7,
                            Title = "Dividend king"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Renewal rates above 90% make revenue very predictable.",
                            CreatedOn = new DateTime(2025, 2, 3, 17, 15, 0, 0, DateTimeKind.Unspecified),
                            StockId = 8,
                            Title = "Membership model"
                        });
                });

            modelBuilder.Entity("backend.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Purchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("lastDividend")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("marketCap")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Apple Inc.",
                            Industry = "Consumer Electronics",
                            Purchase = 227.50m,
                            Symbol = "AAPL",
                            lastDividend = 1.00m,
                            marketCap = 3450000000000L
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Microsoft Corporation",
                            Industry = "Software - Infrastructure",
                            Purchase = 428.10m,
                            Symbol = "MSFT",
                            lastDividend = 3.32m,
                            marketCap = 3180000000000L
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "NVIDIA Corporation",
                            Industry = "Semiconductors",
                            Purchase = 135.40m,
                            Symbol = "NVDA",
                            lastDividend = 0.04m,
                            marketCap = 3320000000000L
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Tesla, Inc.",
                            Industry = "Auto - Manufacturers",
                            Purchase = 248.90m,
                            Symbol = "TSLA",
                            lastDividend = 0.00m,
                            marketCap = 795000000000L
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Amazon.com, Inc.",
                            Industry = "Specialty Retail",
                            Purchase = 196.20m,
                            Symbol = "AMZN",
                            lastDividend = 0.00m,
                            marketCap = 2060000000000L
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "JPMorgan Chase & Co.",
                            Industry = "Banks - Diversified",
                            Purchase = 238.60m,
                            Symbol = "JPM",
                            lastDividend = 5.00m,
                            marketCap = 672000000000L
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "The Coca-Cola Company",
                            Industry = "Beverages - Non-Alcoholic",
                            Purchase = 62.80m,
                            Symbol = "KO",
                            lastDividend = 1.94m,
                            marketCap = 270000000000L
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "Costco Wholesale Corporation",
                            Industry = "Discount Stores",
                            Purchase = 905.30m,
                            Symbol = "COST",
                            lastDividend = 4.64m,
                            marketCap = 401000000000L
                        });
                });

            modelBuilder.Entity("backend.Models.Comment", b =>
                {
                    b.HasOne("backend.Models.Stock", "Stock")
                        .WithMany("Comments")
                        .HasForeignKey("StockId");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("backend.Models.Stock", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
